// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwBiQ0xiWtgp27QUCALW-Q4_pdfFRsdeQ',
    appId: '1:675245868939:web:a6f20bb0dd178bb018918e',
    messagingSenderId: '675245868939',
    projectId: 'mc-ssp-63e5b',
    authDomain: 'mc-ssp-63e5b.firebaseapp.com',
    storageBucket: 'mc-ssp-63e5b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYqSxisMcYCXeCzcy_6GLjXObNVSbcqBY',
    appId: '1:675245868939:android:bab09b4adda1d30d18918e',
    messagingSenderId: '675245868939',
    projectId: 'mc-ssp-63e5b',
    storageBucket: 'mc-ssp-63e5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAACeA5lXb9imNtR-eS4vcnKRYzXRCoZ-0',
    appId: '1:675245868939:ios:9d02c33c68a9c15718918e',
    messagingSenderId: '675245868939',
    projectId: 'mc-ssp-63e5b',
    storageBucket: 'mc-ssp-63e5b.firebasestorage.app',
    iosBundleId: 'com.example.mcSsp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAACeA5lXb9imNtR-eS4vcnKRYzXRCoZ-0',
    appId: '1:675245868939:ios:9d02c33c68a9c15718918e',
    messagingSenderId: '675245868939',
    projectId: 'mc-ssp-63e5b',
    storageBucket: 'mc-ssp-63e5b.firebasestorage.app',
    iosBundleId: 'com.example.mcSsp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwBiQ0xiWtgp27QUCALW-Q4_pdfFRsdeQ',
    appId: '1:675245868939:web:045ae9a50468290018918e',
    messagingSenderId: '675245868939',
    projectId: 'mc-ssp-63e5b',
    authDomain: 'mc-ssp-63e5b.firebaseapp.com',
    storageBucket: 'mc-ssp-63e5b.firebasestorage.app',
  );
}
